clinics/urls.py
from django.urls import path
from .views import *

app_name = "clinics"

urlpatterns = [
	path('', homePage, name='home'),
	path('login', login),
	path('profile/', profile, name='profile'),
	path('addFrequency/', addFrequency, name="addFrequency"),
	path('thanks/', thanks, name="thanks"),
	path('erorr_page/', erorr_page, name='erorr_page'),
	path('admin/', admin, name='admin'),
	path('m_report/', m_report, name='m_report'),
	path('daily_record/', daily_record, name='daily_record'),
	path('recordManage/', recordManage, name='recordManage'),
	path('viewRecords/', DailyReportListView, name='allRecords'),
	path('add_edit_frequency/', add_edit_frequency, name='add_edit_frequency'),
	path('get_cat_vals/', get_cat_vals.as_view(), name='get_cat_vals'),
	
	path('update_record/', update_record.as_view(), name='update_record'),
	
	
	# path('PrintLetter/<int:pk>/',PrintLetter, name='PrintLetter')
	# path('makeAuto', makeAuto) # use to make some actions
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
	path('services/', include('services.urls')),
    path('clinics/', include('clinics.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.urls import path
from .views import *

app_name = "services"

urlpatterns = [
	path('', home, name="home"),
	path('new/', NewLetter, name="NewLetter"),
	path('PrintLetter/<int:pk>/',PrintLetter, name='PrintLetter'),
	#
	path('getDesc/', getDesc),
# 	path('getDesc/<str:q>', getDesc),
	#
	path('editLetter/<int:pk>/',EditLetter.as_view(), name='EditLetter'),
	path('cancelLetter/<int:pk>/',cancelLetter.as_view(), name='cancelLetter'),
	path('get_letter_serial/<int:pk>/',get_letter_serial, name='get_letter_serial'),
	path('ServicePriceCreate/', ServicePriceCreateView.as_view(), name='film_create'),
	path('ServicePriceListView/', ServicePriceListView.as_view(), name='all'),
	path('servicePricesCalc/', servicePricesCalc.as_view()),

]

services/models.py
import datetime
from email.policy import default
from tabnanny import verbose
from unittest.util import _MAX_LENGTH
from django.utils.timezone import now
from django.template.defaultfilters import slugify
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class TimeStampMixin(models.Model):
    is_deleted      = models.BooleanField (default=False)
    created_at      = models.DateTimeField(auto_now_add=True,null=True)
    created_at_date = models.DateField(auto_now_add=True,null=True)
    updated_at      = models.DateTimeField(auto_now=True,null=True)
    updated_at_date = models.DateField(auto_now=True,null=True)

    class Meta:
        abstract = True

    def __str__(self):
        if hasattr(self, 'name'):
            if self.name != None:
                return str(self.name)
            else:
                return str("object")
        else:
                return str("object")



class Area(TimeStampMixin,models.Model):
    name = models.CharField(max_length=100,default='-')

class Law(TimeStampMixin,models.Model):
    name = models.CharField(max_length=100,default='-')

class Ayadat(TimeStampMixin, models.Model):
    name = models.CharField(max_length=50, default="تجربة")
    area = models.ForeignKey('Area', related_name='ayada_area', on_delete=models.CASCADE)
    # is ayada make customer letters or not
    is_letter = models.BooleanField(default=True)

class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    area =  models.ForeignKey('Ayadat', related_name='employee_ayada', on_delete=models.CASCADE, null=True, blank=True)
    area2 = models.ManyToManyField('Ayadat',related_name='employee_ayadat')

class EntityMainClass(TimeStampMixin,models.Model):
    name = models.CharField(max_length=100, default='-', verbose_name='التصنيف الرئيسى', db_index=True)

class EntitySubClass(TimeStampMixin,models.Model):
    name = models.CharField(max_length=100, default='-', verbose_name='التصنيف الرئيسى', db_index=True)

class Entity(TimeStampMixin,models.Model):
    name    = models.CharField(max_length=100, default='-', db_index=True)
    phone   = models.CharField(max_length=20, default='-')
    address = models.CharField(max_length=100, default='-')
    mainClass = models.ForeignKey('EntityMainClass', related_name='entity_main', default=3, on_delete=models.CASCADE, verbose_name="التصنيف الرئيسى",null=True, db_index=True)
    subClass  = models.ForeignKey('EntitySubClass', related_name='entity_sub', default=5, on_delete=models.CASCADE, verbose_name="التصنيف الفرعى",null=True, db_index=True)

# ===

class ServiceMainClass(TimeStampMixin,models.Model):
    name = models.CharField(max_length=100, default='-', verbose_name='التصنيف الرئيسى', db_index=True)

class ServiceSubClass(TimeStampMixin,models.Model):
    name = models.CharField(max_length=100, default='-', verbose_name='التصنيف الفرعى', db_index=True)


class Service(TimeStampMixin,models.Model):
    name      = models.CharField(max_length=250, default='-', verbose_name='اسم الخدمة', db_index=True)
    mainClass = models.ForeignKey('ServiceMainClass', related_name='service_main', on_delete=models.CASCADE, verbose_name="التصنيف الرئيسى",null=True, db_index=True)
    subClass  = models.ForeignKey('ServiceSubClass', related_name='service_sub', on_delete=models.CASCADE, verbose_name="التصنيف الفرعى",null=True, db_index=True)
    code      = models.IntegerField(unique=True,null=True, db_index=True)
    price     = models.IntegerField(unique=True,null=True, blank=True)

class EntityService(TimeStampMixin,models.Model):
    entity   = models.ForeignKey('Entity', related_name='entity_service', on_delete=models.CASCADE, verbose_name="الجهة",null=True, db_index=True)
    services = models.ManyToManyField('Service',related_name='services_entity', default='-')

class Letter(TimeStampMixin,models.Model):
    # first part  patient info
    serial      = models.IntegerField(db_index=True, unique=True, null=True)
    name        = models.CharField(max_length=50, verbose_name="اسم المريض ثلاثى", db_index=True)
    naId        = models.CharField(max_length=14, verbose_name="الرقم القومى", db_index=True)
    by_doctor   = models.CharField(max_length=50, verbose_name="مقرر الإجراء") # doctor
    law         = models.ForeignKey('Law', related_name='letter_law', on_delete=models.CASCADE, verbose_name="قانون الانتفاع")
    ayada       = models.ForeignKey('Ayadat', related_name='letter_law', on_delete=models.CASCADE, verbose_name="العيادة المحول منها")
    diagnosis   = models.CharField(max_length=50, default=" ", verbose_name="التشخيص") # التشخيص
    description = models.TextField(max_length=250, default=" ", verbose_name="وصف الحالة")
    # second part  services info
    price       = models.IntegerField(default=0, verbose_name="الرسوم المقررة")
    services    = models.ManyToManyField('Service', blank=True, related_name='services',verbose_name="الخدمات")
    entity      = models.ForeignKey('Entity', related_name='letter_entity', on_delete=models.CASCADE, verbose_name="الجهة")
    created_by  = models.CharField(max_length=50, default="-", verbose_name="مسئول التسجيل") # created by employee
    notes       = models.CharField(max_length=50, default="", null=True, blank=True)
    cancelReason= models.CharField(max_length=50, default="", null=True, blank=True)


class ServicePrice(TimeStampMixin,models.Model):
    name  = models.ForeignKey('Service', related_name='service_price', on_delete=models.CASCADE, verbose_name="اسم الخدمة")
    publicPrice = models.IntegerField(default=0, verbose_name="توريد المنتفع")
    price = models.IntegerField(default=0, verbose_name="الرسوم المقررة")
    notes = models.CharField(max_length=50, default=" ", verbose_name="ملاحظات")

services/forms.py
from dataclasses import fields
from django import forms
from .models import *
from django.contrib.admin.widgets import FilteredSelectMultiple


class LetterForm(forms.ModelForm):
    # custom_ayada =
    services = forms.ModelMultipleChoiceField(queryset=Service.objects.all(), widget=FilteredSelectMultiple("services", is_stacked=True))
    # ayada    = forms.ModelMultipleChoiceField(queryset=Ayadat.objects.all())
    class Meta:
        model  = Letter

        fields = ['serial','name','naId','by_doctor','law','ayada','diagnosis','description','price','services','entity','created_by']
        # fields = __all__

class sevicePriceForm(forms.ModelForm):
    class Meta:
        model = ServicePrice
        fields = ['name', 'price', 'notes']

services/views.py
from django.shortcuts import redirect, render
from django.urls import is_valid_path, reverse
from rest_framework.views import APIView
from .forms import *
from .models import *
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from rest_framework.response import Response
import json
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q
from django.http import JsonResponse


import random

@csrf_exempt
def getDesc(request):
    q = request.POST.get('q')
    # Construct a query to search for all Letter objects with a description containing the provided phrase
    query = Q(description__icontains=q)
    # Retrieve all matching Letter objects and return their descriptions as a list
    letters = Letter.objects.filter(query)
    descriptions = [letter.description for letter in letters]
    return JsonResponse({'descriptions': descriptions})


def rand_unique_number():
    rNum = random.randint(100,100000)
    rNum_count = Letter.objects.filter(serial=rNum).count()
    while rNum_count > 0:
        rNum = random.randint(100,100000)
    else:
        return rNum

def get_letter_serial(request, pk):
    letter = Letter.objects.get(pk=pk)
    return letter.serial

class priceBaseView(View):
    model = ServicePrice
    fields = '__all__'
    success_url = reverse_lazy('services:all')

class ServicePriceListView(priceBaseView, ListView):
    "list view"

class ServicePriceCreateView(priceBaseView, CreateView):
    """View to create a new film"""
class ServicePriceUpdateView(priceBaseView, UpdateView):
    """View to update a film"""

class ServicePriceDeleteView(priceBaseView, DeleteView):
    """View to delete a film"""

class EditLetter(UpdateView):
    model = Letter
    fields = '__all__'
    randNum = rand_unique_number()
    template_name_suffix = '_edit_form'
    def get_context_data(self,*args, **kwargs):
        context = super(EditLetter, self).get_context_data(*args,**kwargs)
        context['randNum'] = rand_unique_number()
        return context
    # def get_context_data(self, **kwargs):
    #     data = super(EditLetter, self).get_context_data(**kwargs)
    #     data['letterId']=self.object.id
    #     return data
    # letterId = get_context_data()
    def get_success_url(self, **kwargs):
        return reverse_lazy("services:PrintLetter", args=(self.object.id,))

    # success_url = reverse_lazy('services:PrintLetter/${data.letterId}')

class servicePricesCalc(APIView):
    def get(self, request):
        servicesArray = request.GET['services']
        total = 0
        total += [serv.publicPrice for serv in  servicesArray]
        data = {'total':total}
        return Response(data)

class cancelLetter(APIView):
    def get(self, request, pk):
        cancelReason = request.GET['cancelReason']
        Letter.objects.filter(pk=pk).update(is_deleted=True, cancelReason=cancelReason)
        msg = "تم الالغاء"
        data = {'msg': msg}
        return Response(data)

@login_required
def home(request):
    if request.user.groups.filter(name="services_member"):
        pass

    else:
        return redirect('/clinics/profile/')

    if request.method=='POST':
        naId=request.POST.get('naId')
        print(f"naId => ${naId}")
        if naId == 0:
            msg = "خطأ بالرقم القومى"
            return redirect(f'/clinics/erorr_page?msg={msg}')
        else:
            letters = Letter.objects.filter(naId=naId, is_deleted=False)
            msg = "لا يوجد تحويلات سابقة بهذا الرقم القومى" if letters.count() == 0 else 'تم الاستعلام'
            ctx = {'naId':naId,'letters':letters, 'msg':msg}
    elif request.method=='GET':
        ctx = {'naId':''}

    return render(request, 'services/main_page.html', ctx)

def PrintLetter(request, pk):
	letter = Letter.objects.get(id=pk)
	ctx = {'letter':letter}
	return render(request,'services/print_letter.html',ctx)


@login_required
def NewLetter(request):
    user = request.user
    if user.groups.filter(name="services_member"):
        pass
    else:
        return redirect('/clinics/profile')
    randNum =rand_unique_number()
    naId = 2351123
    if request.method=='POST':
        form = LetterForm(request.POST)
        if form.is_valid():
                myform=form.save()
                formId = myform.id
                return redirect(f'/services/PrintLetter/{formId}')
    else:
        naId = str(request.GET.get('naId', ''))
        print("naid => ",naId)
        form = LetterForm()
        userId = request.user.id
        userArea_id =  User.objects.get(pk=userId).employee.area.id
        print(userArea_id)
        if userArea_id != 7:
            # userAyada =  User.objects.get(pk=userId).employee.area.id
            # print(userAyada)
            form.fields["ayada"].queryset = Ayadat.objects.all()
        else:
            form.fields["ayada"].queryset = Ayadat.objects.filter(is_letter=True)
    ctx = {'form1':form, 'randNum':randNum, 'naId':naId}
    return render(request,'services/new_letter.html',ctx)

################ Functions Part

# def auth_user_custom(request):
#     print("here")
#     user = request.user
#     userGroup = ""
#     request.session.setdefault('group', False)
#     if user.groups.filter(name="admin_all"):
#         request.session['group'] = "admin_all"
#         userGroup = "admin_all"
#         return userGroup

#     elif user.groups.filter(name="clinic_admin"):
#         request.session['group'] = "clinic_admin"
#         userGroup = "clinic_admin"
#         return userGroup

#     elif user.groups.filter(name="clinic_supervisor"):
#         request.session['group'] = "clinic_supervisor"
#         userGroup = "clinic_supervisor"
#         return userGroup
#     elif user.groups.filter(name="clinic_member"):
#         request.session['group'] = "clinic_member"
#         userGroup = "clinic_member"
#         return userGroup
#     elif user.groups.filter(name="services_member"):
#         request.session['group'] = "services_member"
#         userGroup = "services_member"
#         return userGroup

#     else:
#         userGroup = "no group"
#         return userGroup

services/templates/services/ServicePrice_form.html
{% extends "index.html" %}

{% block content %}

<!-- BOOTSTRAP FORM -->

<div class="container d-flex justify-content-center mt-5" style="width: 25%;">
    <div class="mt-5">
        <form action="" method="post">
            {% csrf_token %}
            <table class="table">
                {{form.as_table}}
            </table>
            <div class="container d-flex justify-content-center" style="width: 10%;">
                <input type="submit" class="btn btn-primary btn-lg" value="Submit" style="margin-right: 30px; margin-top: 30px;">
                <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{% url 'services:NewLetter' %}'; return false;" value="Cancel">
            </div>    
        </form> 

    </div>
</div>

<!-- END BOOTSTRAP FORM -->

{% endblock %}
{% block script %}
    <script>
        setTimeout(function(){
		  $('#id_name').chosen();
		},300)
    </script>
{% endblock %}

services/templates/services/letter_edit_form.html
{% extends "index.html" %}
<style>
    
</style>
{% block title %}<title>خدمة جديدة</title>{% endblock %}

{% block content %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}

<div class="form_holder p-5 border">
    <form action="#" method="post" class="form" required>
        {% csrf_token %}
        <div class="row">
            <input class="d-none" id="randNum" value="{{randNum}}">
            <input class="d-none" id="urlNaid" value="{{naId}}">
            <div class="col-4">
              {{ form.serial|as_crispy_field }}
            </div>
            <div class="col-4">
              {{ form.name|as_crispy_field }}
            </div>
            <div class="col-4">
              {{ form.naId|as_crispy_field }}
            </div>
            <div class="col-4">
              {{ form.by_doctor|as_crispy_field }}
            </div>
            <hr>
            <div class="col-5">
              {{ form.law|as_crispy_field }}
            </div>
            <div class="col-6">
              {{ form.ayada|as_crispy_field }}
            </div>
            <hr>
            <div class="col-4">
              {{ form.diagnosis|as_crispy_field }}
            </div>
            <div class="col-4">
                {{ form.description|as_crispy_field }}
            </div>
            <div class="col-4">
              {{ form.price|as_crispy_field }}
            </div>
            <hr>
            <div class="col-6" id="id_services_holder">
              <p class="mt-0 mb-0"><label>إختر الخدمة / الخدمات</label></p>
              {{ form.services }}
            </div>
            <div class="col-6 h4">
              {{ form.entity|as_crispy_field }}
            </div>
            <hr>
            <div class="col-4">
                <input id="created_by" class="d-none" value="{{request.user.first_name}} {{request.user.last_name}}">
              {{ form.created_by|as_crispy_field }}
            </div>
            <div class="col-4 mr-auto">
                {% buttons %}
                    <button type="submit" class="btn btn-primary w-100 h-100 d-block" style="margin-top:32px">حفظ وطباعة</button>
                {% endbuttons %}
            </div>
    </form>
</div>
{% endblock %}
{% block script %}
<script>
    setTimeout(function(){
        $(".form-control").css("font-size","1.5rem !important")
        console.log("asssssssss")
    }
    //

    //
    ,500)
  </script>
{% endblock %}

services/templates/services/main_page.html
{% extends "index.html" %}
{% block title %}<title>الرئيسية</title>{% endblock %}
{% block content %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}
<style>
    input.nid-input{
        width: 90%;
        font-size: 1.5rem;
        font-weight: bold;
        text-align: center;
        padding: 5px;
        border-radius: 5%;
        background: #e6eafb;
    }

    input.nid-input:hover{
        border-color: #719ECE  ;
    }

    input.nid-input:focus{
        outline-color: #719ECE;
    }
    .btn{
        font-size: 1.5rem;
    }
</style>
<div class="row mt-5">
    <div class="col-10 text-center m-auto">
        <form class="form" action="/services/" method="post" required>
            <div class="nid-holder">
                    {% csrf_token %}
                    <label for="naId"></label>
                    <input value="{{naId}}" class="form-control text-center" id="naId" name="naId" type="text" maxlength="14" minlength="14" required
                    placeholder="الرقم القومى">
                    <br>
            </div>
            <div class="mt-5">
                    <input class="btn btn-warning text-white d-100 p-2 h1 ml-5" id="search" type="submit" value="بحث عن منتفع">
                    <a class="btn btn-info d-100 p-2 h1" id="newLetterLink" href="">خطاب تحويل جديد</a>
            </div>
        </form>
    </div>
</div>
<div class="row text-center mt-5">
    <div class="col-11 m-auto text-danger">
        <h3 class="h3">
            {% if msg %}
            {{msg}}
            <hr>
            <div class="table-holder"></div>
                <table class="table text-center h5 table-responsive table-bordered table-hovered">
                    <thead>
                        <tr class="bg-dark text-white">
                            <th>أمر 1</th>
                            <th>أمر 2</th>
                            <th>أمر 3</th>
                            <th>اسم المنتفع</th>
                            <th>رقم خطاب التحويل</th>
                            <th>تاريخ التحويل</th>
                            <th>الجهة المحول اليها</th>
                            <th>الخدمة/الخدمات</th>
                            
                        </tr>
                    </thead>
                    {%for letter in letters%}
                    <tbody>
                        <tr id="{{letter.id}}">
                            <td><a class="btn btn-danger text-white cancel" letterId="{{letter.id}}">الغاء</a></td>
                            <td>
                                <input type="hidden" value="{{letter.id}}" id="letterId">
                                <a class="btn btn-info text-white edit editLink" letterId="{{letter.id}}"
                                href="#">تعديل</a>
                            <input type="hidden" value="" id="naIdEdit">
                        </td>
                            <td><a class="btn btn-success" href="/services/PrintLetter/{{letter.id}}">طباعة</a>
                            </td>
                            <td>{{letter.name}}</td>
                            <td>{{letter.serial}}</td>
                            <td>{{letter.created_at|date:"Y/m/d" }}</td>
                            <td>{{letter.entity.name}}</td>
                            <td>
                                {{ letter.services.all|join:" / " }}
                            </td>
                        </tr>
                    </tbody>
                    {% endfor %}
                </table>
            </div>
            
            {% else %}
            ادخل الرقم القومى واضغط بحث
            {% endif %}</h3>
    </div>
</div>
<script>
    console.log("working")
    setTimeout(() => {
        $("input#naIdEdit").attr("value", $("input#naId").val());
        $(".editLink").each(function() {
            let letterId = $($(this)).prev("input").val(),
                naId = $(this).next("input").val();
            $(this).attr("href", `editLetter/${letterId}/?naId=${naId}`)
        })
    }, 900);
</script>
{% endblock %}
{% block script %}
<script>
	$("a.cancel").click(function(){
		let letterid = $(this).attr("letterid")
		
        Swal.fire({
			title: 'سبب الالغاء',
			input: 'text',
			inputAttributes: {
				autocapitalize: 'off',
				required : 'required',
				style :"display: flex; text-align:right"
			},
			showCancelButton: true,
			confirmButtonText: 'الغاء الخطاب',
			cancelButtonText: 'رجوع',
			showLoaderOnConfirm: true,
			preConfirm: (login) => {
				return fetch(`/services/cancelLetter/${letterid}?cancelReason="test"`)
				.then(response => {
					if (!response.ok) {
					throw new Error(response.statusText)
					}
					return response.json()
				})
				.catch(error => {
					Swal.showValidationMessage(
					`Request failed: ${error}`
					)
				})
			},
			allowOutsideClick: () => !Swal.isLoading()
			}).then((result) => {
			if (result.isConfirmed) {
				Swal.fire({
				title: 'تم الغاء الخطاب',
				})
				
				setTimeout(function(){
					location.reload()
				}, 1000)
			}
			
			})
		

    })
	</script>
	<script>

		$("#naId").keyup(function(){
			let naId = $(this).val();
			// console.log('naid => ', naId);
			if (naId.length == 14){
				$("#newLetterLink").attr('href', `/services/new?naId=${naId}`)
			}
		})

		setInterval(function(){
			let naId = $("#naId").val();
			if (naId.length == 14){
                console.log("saaaaaaaaaaa")
				$("#newLetterLink").attr('href', `/services/new?naId=${naId}`)
			}
		},500)
		
	</script>

	<script>
		setTimeout(() => {
			let naId = $("#urlNaid").val();
			console.log("naId => ", naId);
			$("#div_id_naId #id_naId").attr('value', naId);
		}, 900);
        
		// $("input.nid-input").click(function(){
		// 	$(this).css({'border-color': '#0000ff'});
		// })
	</script>
{% endblock %}

services/templates/services/new_letter.html
{% extends "index.html" %}
<style>

</style>
{% block title %}<title>خدمة جديدة</title>{% endblock %}

{% block content %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}

<div class="form_holder p-5 border">
    <form action="#" method="post" class="form" required>
        {% csrf_token %}
        <div class="row">
            <input class="d-none" id="randNum" value="{{randNum}}">
            <input class="d-none" id="urlNaid" value="{{naId}}">
            <div class="col-4">
              {{ form1.serial|as_crispy_field }}
            </div>
            <div class="col-4">
              {{ form1.name|as_crispy_field }}
            </div>
            <div class="col-4">
              {{ form1.naId|as_crispy_field }}
            </div>
            <div class="col-4">
              {{ form1.by_doctor|as_crispy_field }}
            </div>
            <hr>
            <div class="col-5">
              {{ form1.law|as_crispy_field }}
            </div>
            <div class="col-6">
              {{ form1.ayada|as_crispy_field }}
            </div>
            <hr>
            <div class="col-4">
              {{ form1.diagnosis|as_crispy_field }}
            </div>
            <div class="col-4">
                <div class="w-100" id="sug_holders">
                    <input class="w-100" list="descs" id="fruits" name="fruits">
                    <datalist id="descs">
                        <option>test</option>
                    </datalist>
                </div>
                {{ form1.description|as_crispy_field }}

            </div>
            <div class="col-4">
              {{ form1.price|as_crispy_field }}
            </div>
            <hr>
            <div class="col-6" id="id_services_holder">
              <p class="mt-0 mb-0"><label>إختر الخدمة / الخدمات</label></p>
              {{ form1.services }}
            </div>
            <div class="col-6 h4">
              {{ form1.entity|as_crispy_field }}
            </div>
            <hr>
            <div class="col-4">
                <input id="created_by" class="d-none" value="{{request.user.first_name}} {{request.user.last_name}}">
              {{ form1.created_by|as_crispy_field }}
            </div>
            <div class="col-4 mr-auto">
                {% buttons %}
                    <button type="submit" class="btn btn-primary w-100 h-100 d-block" style="margin-top:32px">حفظ وطباعة</button>
                {% endbuttons %}
            </div>
    </form>
</div>
{% endblock %}
{% block script %}
<script>
  $(".form-control").css("font-size","1.5rem !important")
  // get previous descriptions
  $("#id_description").keyup(function(){
      let q = $(this).val();
      console.log(q)
      $.ajax({
      url: `/services/getDesc/`,
      type: 'POST',
      dataType: 'json',
      data: {
        q: q,
      },
      success: function(data) {
        // console.log('data received:', data['descriptions']);
        var descriptions = data.descriptions;

        for (var i = 0; i < data.length; i++) {
          console.log(`data${i} => ${data}`)
        }

      },
      error: function(xhr, status, error) {
        console.log('Error:', error);
      }
    });
  })


</script>
{% endblock %}

services/templates/services/serviceprice_list.html
{% extends "index.html" %}

{% block content %}

<!-- BOOTSTRAP FORM -->

<div class="row">
    <div class="col-12 text-center">
        <table class="table table-bordered table-hovered">
            <thead class="bg-dark text-white">
                <tr>
                    <th>اسم الخدمة</th>
                    <th>سعر الخدمة</th>
                    <th>ملاحظات</th>
                </tr>
            </thead>
            <tbody>
                {% for service in object_list %}
                <tr>
                    <td>{{service.name}}</td>
                    <td>{{service.price}}</td>
                    <td>{{service.notes}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<!-- END BOOTSTRAP FORM -->

{% endblock %}
{% block script %}
    <script>
        setTimeout(function(){
		  $('#id_name').chosen();
		},300)
    </script>
{% endblock %}